version : '3'
services : 
  backend :
    build : backend 
    ports: 
      - 8080:8080
    
  frontend :
    build : frontend
    ports : 
      - 3000:3000

  mongodb : 
    image : mongo:latest
    restart : always
    container_name : mongodb 
    ports : 
      - 27017:27017